package net.geoprism.registry.etl.export;

@com.runwaysdk.business.ClassSignature(hash = -243945724)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DataExportJob.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class DataExportJobBase extends com.runwaysdk.system.scheduler.ExecutableJob
{
  public final static String CLASS = "net.geoprism.registry.etl.export.DataExportJob";
  private static final long serialVersionUID = -243945724;
  
  public DataExportJobBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static DataExportJobQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    DataExportJobQuery query = new DataExportJobQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static DataExportJob get(String oid)
  {
    return (DataExportJob) com.runwaysdk.business.Business.get(oid);
  }
  
  public static DataExportJob getByKey(String key)
  {
    return (DataExportJob) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static DataExportJob lock(java.lang.String oid)
  {
    DataExportJob _instance = DataExportJob.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static DataExportJob unlock(java.lang.String oid)
  {
    DataExportJob _instance = DataExportJob.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
