/**
 * Copyright (c) 2022 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Geoprism Registry(tm).
 *
 * Geoprism Registry(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Geoprism Registry(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Geoprism Registry(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package net.geoprism.registry.io;

@com.runwaysdk.business.ClassSignature(hash = -1944410550)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ParentCodeException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class ParentCodeExceptionBase extends com.runwaysdk.business.SmartException
{
  public final static String CLASS = "net.geoprism.registry.io.ParentCodeException";
  public static java.lang.String CONTEXT = "context";
  public static java.lang.String OID = "oid";
  public static java.lang.String PARENTCODE = "parentCode";
  public static java.lang.String PARENTTYPE = "parentType";
  private static final long serialVersionUID = -1944410550;
  
  public ParentCodeExceptionBase()
  {
    super();
  }
  
  public ParentCodeExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public ParentCodeExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public ParentCodeExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getContext()
  {
    return getValue(CONTEXT);
  }
  
  public void validateContext()
  {
    this.validateAttribute(CONTEXT);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getContextMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.io.ParentCodeException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(CONTEXT);
  }
  
  public void setContext(String value)
  {
    if(value == null)
    {
      setValue(CONTEXT, "");
    }
    else
    {
      setValue(CONTEXT, value);
    }
  }
  
  public String getOid()
  {
    return getValue(OID);
  }
  
  public void validateOid()
  {
    this.validateAttribute(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.io.ParentCodeException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(OID);
  }
  
  public String getParentCode()
  {
    return getValue(PARENTCODE);
  }
  
  public void validateParentCode()
  {
    this.validateAttribute(PARENTCODE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getParentCodeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.io.ParentCodeException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(PARENTCODE);
  }
  
  public void setParentCode(String value)
  {
    if(value == null)
    {
      setValue(PARENTCODE, "");
    }
    else
    {
      setValue(PARENTCODE, value);
    }
  }
  
  public String getParentType()
  {
    return getValue(PARENTTYPE);
  }
  
  public void validateParentType()
  {
    this.validateAttribute(PARENTTYPE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getParentTypeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.io.ParentCodeException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(PARENTTYPE);
  }
  
  public void setParentType(String value)
  {
    if(value == null)
    {
      setValue(PARENTTYPE, "");
    }
    else
    {
      setValue(PARENTTYPE, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{context}", this.getContext());
    message = replace(message, "{oid}", this.getOid());
    message = replace(message, "{parentCode}", this.getParentCode());
    message = replace(message, "{parentType}", this.getParentType());
    return message;
  }
  
}
