package net.geoprism.registry;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 *
 * @author Autogenerated by RunwaySDK
 */
@com.runwaysdk.business.ClassSignature(hash = 180741560)
public enum ChangeFrequency implements com.runwaysdk.business.BusinessEnumeration
{
  ANNUAL(),
  
  BIANNUAL(),
  
  DAILY(),
  
  MONTHLY(),
  
  QUARTER();
  
  public static final java.lang.String CLASS = "net.geoprism.registry.ChangeFrequency";
  private net.geoprism.registry.ChangeFrequencyMaster enumeration;
  
  private synchronized void loadEnumeration()
  {
    net.geoprism.registry.ChangeFrequencyMaster enu = net.geoprism.registry.ChangeFrequencyMaster.getEnumeration(this.name());
    setEnumeration(enu);
  }
  
  private synchronized void setEnumeration(net.geoprism.registry.ChangeFrequencyMaster enumeration)
  {
    this.enumeration = enumeration;
  }
  
  public java.lang.String getOid()
  {
    loadEnumeration();
    return enumeration.getOid();
  }
  
  public java.lang.String getEnumName()
  {
    loadEnumeration();
    return enumeration.getEnumName();
  }
  
  public java.lang.String getDisplayLabel()
  {
    loadEnumeration();
    return enumeration.getDisplayLabel().getValue(com.runwaysdk.session.Session.getCurrentLocale());
  }
  
  public static ChangeFrequency get(String oid)
  {
    for (ChangeFrequency e : ChangeFrequency.values())
    {
      if (e.getOid().equals(oid))
      {
        return e;
      }
    }
    return null;
  }
  
}
