package net.geoprism.registry.jobs;

@com.runwaysdk.business.ClassSignature(hash = -218369972)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GPRJobHistory.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class GPRJobHistoryBase extends com.runwaysdk.system.scheduler.JobHistory
{
  public final static String CLASS = "net.geoprism.registry.jobs.GPRJobHistory";
  public final static java.lang.String COMPLETEDROWSJSON = "completedRowsJson";
  public final static java.lang.String CONFIGJSON = "configJson";
  public final static java.lang.String GEOOBJECTTYPECODE = "geoObjectTypeCode";
  public final static java.lang.String ORGANIZATION = "organization";
  public final static java.lang.String STAGE = "stage";
  public final static java.lang.String TYPES = "types";
  @SuppressWarnings("unused")
  private static final long serialVersionUID = -218369972;
  
  public GPRJobHistoryBase()
  {
    super();
  }
  
  public String getCompletedRowsJson()
  {
    return getValue(COMPLETEDROWSJSON);
  }
  
  public void validateCompletedRowsJson()
  {
    this.validateAttribute(COMPLETEDROWSJSON);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getCompletedRowsJsonMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.jobs.GPRJobHistory.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(COMPLETEDROWSJSON);
  }
  
  public void setCompletedRowsJson(String value)
  {
    if(value == null)
    {
      setValue(COMPLETEDROWSJSON, "");
    }
    else
    {
      setValue(COMPLETEDROWSJSON, value);
    }
  }
  
  public String getConfigJson()
  {
    return getValue(CONFIGJSON);
  }
  
  public void validateConfigJson()
  {
    this.validateAttribute(CONFIGJSON);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeJsonDAOIF getConfigJsonMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.jobs.GPRJobHistory.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeJsonDAOIF)mdClassIF.definesAttribute(CONFIGJSON);
  }
  
  public void setConfigJson(String value)
  {
    if(value == null)
    {
      setValue(CONFIGJSON, "");
    }
    else
    {
      setValue(CONFIGJSON, value);
    }
  }
  
  public String getGeoObjectTypeCode()
  {
    return getValue(GEOOBJECTTYPECODE);
  }
  
  public void validateGeoObjectTypeCode()
  {
    this.validateAttribute(GEOOBJECTTYPECODE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getGeoObjectTypeCodeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.jobs.GPRJobHistory.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(GEOOBJECTTYPECODE);
  }
  
  public void setGeoObjectTypeCode(String value)
  {
    if(value == null)
    {
      setValue(GEOOBJECTTYPECODE, "");
    }
    else
    {
      setValue(GEOOBJECTTYPECODE, value);
    }
  }
  
  public net.geoprism.registry.Organization getOrganization()
  {
    if (getValue(ORGANIZATION).trim().equals(""))
    {
      return null;
    }
    else
    {
      return net.geoprism.registry.Organization.get(getValue(ORGANIZATION));
    }
  }
  
  public String getOrganizationOid()
  {
    return getValue(ORGANIZATION);
  }
  
  public void validateOrganization()
  {
    this.validateAttribute(ORGANIZATION);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF getOrganizationMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.jobs.GPRJobHistory.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF)mdClassIF.definesAttribute(ORGANIZATION);
  }
  
  public void setOrganization(net.geoprism.registry.Organization value)
  {
    if(value == null)
    {
      setValue(ORGANIZATION, "");
    }
    else
    {
      setValue(ORGANIZATION, value.getOid());
    }
  }
  
  public void setOrganizationId(java.lang.String oid)
  {
    if(oid == null)
    {
      setValue(ORGANIZATION, "");
    }
    else
    {
      setValue(ORGANIZATION, oid);
    }
  }
  
  @SuppressWarnings("unchecked")
  public java.util.List<net.geoprism.registry.etl.ImportStage> getStage()
  {
    return (java.util.List<net.geoprism.registry.etl.ImportStage>) getEnumValues(STAGE);
  }
  
  public void addStage(net.geoprism.registry.etl.ImportStage value)
  {
    if(value != null)
    {
      addEnumItem(STAGE, value.getOid());
    }
  }
  
  public void removeStage(net.geoprism.registry.etl.ImportStage value)
  {
    if(value != null)
    {
      removeEnumItem(STAGE, value.getOid());
    }
  }
  
  public void clearStage()
  {
    clearEnum(STAGE);
  }
  
  public void validateStage()
  {
    this.validateAttribute(STAGE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF getStageMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.jobs.GPRJobHistory.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeEnumerationDAOIF)mdClassIF.definesAttribute(STAGE);
  }
  
  public String getTypes()
  {
    return getValue(TYPES);
  }
  
  public void validateTypes()
  {
    this.validateAttribute(TYPES);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeJsonDAOIF getTypesMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.jobs.GPRJobHistory.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeJsonDAOIF)mdClassIF.definesAttribute(TYPES);
  }
  
  public void setTypes(String value)
  {
    if(value == null)
    {
      setValue(TYPES, "");
    }
    else
    {
      setValue(TYPES, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static GPRJobHistoryQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    GPRJobHistoryQuery query = new GPRJobHistoryQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public com.runwaysdk.business.Relationship addGeometryTable(com.runwaysdk.business.Business geometryTable)
  {
    return (com.runwaysdk.business.Relationship) addChild(geometryTable, "net.geoprism.registry.geometry.JobHistoryGeometry");
  }
  
  public void removeGeometryTable(com.runwaysdk.business.Business geometryTable)
  {
    removeAllChildren(geometryTable, "net.geoprism.registry.geometry.JobHistoryGeometry");
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.business.Business> getAllGeometryTable()
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.business.Business>) getChildren("net.geoprism.registry.geometry.JobHistoryGeometry");
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.business.Relationship> getAllGeometryTableRel()
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.business.Relationship>) getChildRelationships("net.geoprism.registry.geometry.JobHistoryGeometry");
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.business.Relationship> getGeometryTableRel(com.runwaysdk.business.Business geometryTable)
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.business.Relationship>) getRelationshipsWithChild(geometryTable, "net.geoprism.registry.geometry.JobHistoryGeometry");
  }
  
  public static GPRJobHistory get(String oid)
  {
    return (GPRJobHistory) com.runwaysdk.business.Business.get(oid);
  }
  
  public static GPRJobHistory getByKey(String key)
  {
    return (GPRJobHistory) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static GPRJobHistory lock(java.lang.String oid)
  {
    GPRJobHistory _instance = GPRJobHistory.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static GPRJobHistory unlock(java.lang.String oid)
  {
    GPRJobHistory _instance = GPRJobHistory.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
