package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1796657403)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to BusinessEdgeType.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class BusinessEdgeTypeQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = -1796657403;

  protected BusinessEdgeTypeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.BusinessEdgeTypeDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.BusinessEdgeTypeDTO>)super.getResultSet();
}
}
