package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1155109122)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DuplicateGeoObjectTypeException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class DuplicateGeoObjectTypeExceptionBase extends com.runwaysdk.business.SmartException
{
  public final static String CLASS = "net.geoprism.registry.DuplicateGeoObjectTypeException";
  public static java.lang.String DUPLICATEVALUE = "duplicateValue";
  public static java.lang.String OID = "oid";
  private static final long serialVersionUID = -1155109122;
  
  public DuplicateGeoObjectTypeExceptionBase()
  {
    super();
  }
  
  public DuplicateGeoObjectTypeExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public DuplicateGeoObjectTypeExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public DuplicateGeoObjectTypeExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getDuplicateValue()
  {
    return getValue(DUPLICATEVALUE);
  }
  
  public void validateDuplicateValue()
  {
    this.validateAttribute(DUPLICATEVALUE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getDuplicateValueMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.DuplicateGeoObjectTypeException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(DUPLICATEVALUE);
  }
  
  public void setDuplicateValue(String value)
  {
    if(value == null)
    {
      setValue(DUPLICATEVALUE, "");
    }
    else
    {
      setValue(DUPLICATEVALUE, value);
    }
  }
  
  public String getOid()
  {
    return getValue(OID);
  }
  
  public void validateOid()
  {
    this.validateAttribute(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.DuplicateGeoObjectTypeException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeUUIDDAOIF)mdClassIF.definesAttribute(OID);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{duplicateValue}", this.getDuplicateValue());
    message = replace(message, "{oid}", this.getOid());
    return message;
  }
  
}
