package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1370782786)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to HierarchicalRelationshipTypeDisplayLabel.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class HierarchicalRelationshipTypeDisplayLabelQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = -1370782786;

  protected HierarchicalRelationshipTypeDisplayLabelQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.HierarchicalRelationshipTypeDisplayLabelDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.HierarchicalRelationshipTypeDisplayLabelDTO>)super.getResultSet();
}
}
