package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1271527704)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ListTypeVersionGeospatialDescription.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ListTypeVersionGeospatialDescriptionQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = -1271527704;

  protected ListTypeVersionGeospatialDescriptionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.ListTypeVersionGeospatialDescriptionDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.ListTypeVersionGeospatialDescriptionDTO>)super.getResultSet();
}
}
