package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1095007415)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ListTypeGeoObjectTypeGroup.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ListTypeGeoObjectTypeGroupQueryDTO extends net.geoprism.registry.ListTypeGroupQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = -1095007415;

  protected ListTypeGeoObjectTypeGroupQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.ListTypeGeoObjectTypeGroupDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.ListTypeGeoObjectTypeGroupDTO>)super.getResultSet();
}
}
