package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = 1881408483)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ListTypeGeospatialAcknowledgements.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ListTypeGeospatialAcknowledgementsQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = 1881408483;

  protected ListTypeGeospatialAcknowledgementsQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.ListTypeGeospatialAcknowledgementsDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.ListTypeGeospatialAcknowledgementsDTO>)super.getResultSet();
}
}
