package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1592978875)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ListTypeListLabel.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ListTypeListLabelQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = -1592978875;

  protected ListTypeListLabelQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.ListTypeListLabelDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.ListTypeListLabelDTO>)super.getResultSet();
}
}
