package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = -1296283536)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ListTypeVersionListProcess.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ListTypeVersionListProcessQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = -1296283536;

  protected ListTypeVersionListProcessQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.ListTypeVersionListProcessDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.ListTypeVersionListProcessDTO>)super.getResultSet();
}
}
