package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = 619873145)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MasterListDisplayLabel.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MasterListDisplayLabelQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = 619873145;

  protected MasterListDisplayLabelQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.MasterListDisplayLabelDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.MasterListDisplayLabelDTO>)super.getResultSet();
}
}
