package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = 863202805)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MasterListAccessConstraintsLocal.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MasterListAccessConstraintsLocalQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = 863202805;

  protected MasterListAccessConstraintsLocalQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.MasterListAccessConstraintsLocalDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.MasterListAccessConstraintsLocalDTO>)super.getResultSet();
}
}
