package net.geoprism.registry;

@com.runwaysdk.business.ClassSignature(hash = 80536490)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to UndirectedGraphTypeDisplayLabel.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class UndirectedGraphTypeDisplayLabelQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = 80536490;

  protected UndirectedGraphTypeDisplayLabelQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.UndirectedGraphTypeDisplayLabelDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.UndirectedGraphTypeDisplayLabelDTO>)super.getResultSet();
}
}
