#tile.threads=4
#import.refreshSessionRecordCount=10000
cgr.cors.whitelist=*
cgr.map.bounds=[[-125.0011, 24.9493], [-66.9326, 49.5904]]
cgr.graph.visualizer.enabled=true
enable.business.data=true
enable.labeled.property.graph=true
mapboxgl.accessToken=changeit
