package net.geoprism.registry.etl;

@com.runwaysdk.business.ClassSignature(hash = 197304179)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to PublishListTypeJob.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class PublishListTypeJobBase extends net.geoprism.registry.etl.ListTypeJob
{
  public final static String CLASS = "net.geoprism.registry.etl.PublishListTypeJob";
  private static final long serialVersionUID = 197304179;
  
  public PublishListTypeJobBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static PublishListTypeJobQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    PublishListTypeJobQuery query = new PublishListTypeJobQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static PublishListTypeJob get(String oid)
  {
    return (PublishListTypeJob) com.runwaysdk.business.Business.get(oid);
  }
  
  public static PublishListTypeJob getByKey(String key)
  {
    return (PublishListTypeJob) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static PublishListTypeJob lock(java.lang.String oid)
  {
    PublishListTypeJob _instance = PublishListTypeJob.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static PublishListTypeJob unlock(java.lang.String oid)
  {
    PublishListTypeJob _instance = PublishListTypeJob.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
