package net.geoprism.registry.etl;

@com.runwaysdk.business.ClassSignature(hash = 100243931)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to PublishMasterListJob.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class PublishMasterListJobBase extends net.geoprism.registry.etl.MasterListJob
{
  public final static String CLASS = "net.geoprism.registry.etl.PublishMasterListJob";
  private static final long serialVersionUID = 100243931;
  
  public PublishMasterListJobBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static PublishMasterListJobQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    PublishMasterListJobQuery query = new PublishMasterListJobQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static PublishMasterListJob get(String oid)
  {
    return (PublishMasterListJob) com.runwaysdk.business.Business.get(oid);
  }
  
  public static PublishMasterListJob getByKey(String key)
  {
    return (PublishMasterListJob) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static PublishMasterListJob lock(java.lang.String oid)
  {
    PublishMasterListJob _instance = PublishMasterListJob.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static PublishMasterListJob unlock(java.lang.String oid)
  {
    PublishMasterListJob _instance = PublishMasterListJob.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
