/**
 * Copyright (c) 2022 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Geoprism Registry(tm).
 *
 * Geoprism Registry(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Geoprism Registry(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Geoprism Registry(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package net.geoprism.registry.etl;

@com.runwaysdk.business.ClassSignature(hash = 100243931)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to PublishMasterListJob.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class PublishMasterListJobBase extends net.geoprism.registry.etl.MasterListJob
{
  public final static String CLASS = "net.geoprism.registry.etl.PublishMasterListJob";
  private static final long serialVersionUID = 100243931;
  
  public PublishMasterListJobBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static PublishMasterListJobQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    PublishMasterListJobQuery query = new PublishMasterListJobQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static PublishMasterListJob get(String oid)
  {
    return (PublishMasterListJob) com.runwaysdk.business.Business.get(oid);
  }
  
  public static PublishMasterListJob getByKey(String key)
  {
    return (PublishMasterListJob) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static PublishMasterListJob lock(java.lang.String oid)
  {
    PublishMasterListJob _instance = PublishMasterListJob.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static PublishMasterListJob unlock(java.lang.String oid)
  {
    PublishMasterListJob _instance = PublishMasterListJob.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
